/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coverity.java.test;

public class App {

    public static void main(String[] args) {
        App app = new App();
        app.testInstanceofNull("test string");
        app.testInstanceofNull(null);

        app.testAssertionMethod("2nd test string");

        try {
            app.testAssertionMethod(null);
        } catch (RuntimeException e) {
            System.out.println("This should throw a runtime exception");
        }
    }

    public void testInstanceofNull(Object s) {
        if (s instanceof String) {
            System.out.println("The string s has " + ((String) s).length() + " characters");
        } else {
            System.out.println("String s is NULL");
        }
    }

    public void testAssertionMethod(String s) {
        Utils.assertNotNull(s);
        System.out.println("String length is " + s.length());
    }
}
